### ISSUE TITLE
No rewards given on the new Daily mission.

### ISSUE THREAD

**Issue by Mohdira** [MobulaFi/mobula-feedbacks#236] opened 2023-07-25 15:05 UTC
The new Daily mission about founder Sacha's request to follow his Twitter account,which i already did.
I have tried also to unfollow and follow back to see difference,
But upon going back to Metamask page,the rewards are not given and still indicating that i have not liked it and maybe his other tweets.
Below is are two screenshots to show am a follower of his account and have done as tasked but nothing changed and still shows the daily mission is on.

![image](https://github.com/MobulaFi/mobula-feedbacks/assets/136676391/9e1598b0-c2b6-4ad2-af59-070f472e3b1d)

![image](https://github.com/MobulaFi/mobula-feedbacks/assets/136676391/bc0d67c7-52cf-46be-a9e2-aae0c3e163ee)

Bug being reported from Iphone XR

**Comment by NBMSacha** [comment] 2023-07-29 13:05
Duplicate of #234 !!

**Closed by NBMSacha** 2023-07-29 13:05 UTC
