### ISSUE TITLE
Dao voting issue

### ISSUE THREAD

**Issue by BrianArunga** [MobulaFi/mobula-feedbacks#79] opened 2023-03-31 19:33 UTC
**Describe the bug**
Since the implementation of the timer which indeed was compulsory to be there,on my end since yesterday I've been having trouble with voting both on rank 1 and rank 2 giving errors

Yesterday i had an issue voting on Rank 2 but managed to vote on Rank 1 
Today had an issue voting on rank 1 but managed to vote on rank 2 ...tapping on validate vote system doesn't respond and that makes me not to perform my Dao duties..can't say it's my network because all along it was loading both first and send sorts well.

**To Reproduce**
1. Go to Protocol dao
2. Click on first sort
3. Scroll down to "be listed token"

**Expected behavior**
When tapping on validate it should respond to  allow me vote .

**Screenshots**
![Screenshot_20230331_124909_Trust Wallet.jpg](https://user-images.githubusercontent.com/106274740/229212571-0880a36f-428c-4780-99ae-847552f264a7.jpg)

**Desktop (please complete the following information):**
 - 

**Smartphone (please complete the following information):**
 - Device: A73 Samsung 
 - Android 13

**Additional context**

**Comment by NBMSacha** [comment] 2023-04-04 18:30
This is a duplicate of #78. Thanks!

**Closed by NBMSacha** 2023-04-04 18:30 UTC
