### ISSUE TITLE
In my portfolio, the balance of the trust jack wallet is incorrectly displayed.  There are 1022 mobules in my wallet, 1710 in my portfolio, 0.000068usdc in my wallet, 1.000 in my portfolio

### ISSUE THREAD

**Issue by Alex7xx** [MobulaFi/mobula-feedbacks#154] opened 2023-05-24 03:37 UTC
**Describe the bug**
A clear and concise description of what the bug is.In my portfolio, the balance of the trust jack wallet is incorrectly displayed.  There are 1022 mobules in my wallet, 1710 in my portfolio, 0.000068usdc in my wallet, 1.000 in my portfolio

**To Reproduce**

**Expected behavior**

**Screenshots**
![Screenshot_20230523-211659_Trust Wallet](https://github.com/MobulaFi/mobula-feedbacks/assets/129584554/b6b78054-daae-4589-823d-798c482f89df)
![Screenshot_20230523-211659_Trust Wallet](https://github.com/MobulaFi/mobula-feedbacks/assets/129584554/2f7e4745-6bc4-49b0-bee3-300bfb769fa7)
![Screenshot_20230523-211546_Chrome](https://github.com/MobulaFi/mobula-feedbacks/assets/129584554/f9d2c736-425a-4d55-b889-b4832e40deb5)
![Screenshot_20230523-165320_Chrome](https://github.com/MobulaFi/mobula-feedbacks/assets/129584554/8bafd7c8-de7f-4ff4-aa92-de43da8e2f58)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [e.g. smartfon Samsung a3
 - OS: [e.g. iOS8.1] android 8.1
 - Browser [Googlehrom 
 - Version [113.0.5672.131

**Additional context**

**Comment by anouci** [comment] 2023-06-30 14:11
The problem is being fixed by the team

**Closed by anouci** 2023-06-30 14:11 UTC
